version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit-queue
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@rabbit-queue
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
  syncengine-db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: syncengine-db
    environment:
        SA_PASSWORD: "p@ssword"
        ACCEPT_EULA: "Y"
    ports: 
      - "1433:1433"
    restart: always
