version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit-queue
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@rabbit-queue
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
  syncengine-api:
    image: syncengine-api:latest
    depends_on:
      - "rabbitmq"
      - "postgresql"
    build:
      context: ./SyncEngine.Api/
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
  zoho-worker:
    image: zoho-worker:latest
    depends_on:
      - "rabbitmq"
      - "postgresql"
    build: 
      context: ./Zoho.Worker/
      dockerfile: Dockerfile