
IF NOT EXISTS (SELECT 1
FROM INFORMATION_SCHEMA.TABLES AS it
WHERE it.TABLE_NAME = 'Client')
BEGIN
    CREATE TABLE Client
    (
        ClientId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Client PRIMARY KEY CLUSTERED DEFAULT NEWID(),
        Name VARCHAR(50) NOT NULL
    )
END;

IF NOT EXISTS (SELECT 1
FROM INFORMATION_SCHEMA.TABLES AS it
WHERE it.TABLE_NAME = 'Transaction')
BEGIN
    CREATE TABLE [Transaction]
    (
        TransactionId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Transaction PRIMARY KEY CLUSTERED,
        ClientId UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_TransactionClient FOREIGN KEY REFERENCES Client (ClientId),
        [FileName] VARCHAR(50) NULL,
        SafeFileName VARCHAR(50) NULL,
        CreatedOn DATETIME2(2) NOT NULL CONSTRAINT DF_TransactionCreatedOn DEFAULT GETDATE()
    )
END;


IF EXISTS (SELECT 1
FROM INFORMATION_SCHEMA.TABLES AS it
WHERE it.TABLE_NAME = 'Client')
BEGIN
    INSERT INTO Client
        (Name)
    VALUES
        ('Noble Truss'),
        ('Test Client');
END;
